### PR TITLE
[Feature] Ability to generate the magnetic field vector in apex coordinates.

### PR DESCRIPTION
**Pull request by asreimer**
This pull request adds two new methods to the Apex class, `get_babs` and `apex_bvectors`.

## Purpose
When working with electric fields and/or velocities, it can be desirable to convert between electric field and velocity. For example, if one has generated electric fields by taking the gradient of the potential from an empirical potential model, one may want to also determine the ExB velocity. To do this, one needs the B vector in apex coordinates (B_e3 times by e3).

## New functionality
`apex_bvectors` returns both B_e3 and B_d3 and the e3 and d3 scaled basis vectors. In order to determine B_e3 and B_d3, one need to know the magnitude of the IGRF magnetic field, hence the creation of the `get_babs` method.

## Modifications
`apex.py` was modified. Also, the `test_Apex.py` was modified to include tests for `get_babs` and `apex_bvectors`. Finally, the `test_fortranapex.py` tests were modified so that the fortran library was properly initialized for each test. Having the initialization outside of each test meant that the fortran library could be re-initialized to a different date by another test. This is because pytest imports things and then later runs the tests...

I modified `apex.py` to use `ctypes` to access the `fortranapex.so` shared object file produced by f2py during execution of setup.py. This was so that I could access the FELDG fortran subroutine provided in the `magfld.f` file to get the IGRF B field strength **without** needing to modify the `magfld.f`or writing an additional fortran wrapper with intents. As per #14, we want to head in the direction of using `ctypes` anyways, so that also motivated the choise.

### get_babs

    import apexpy
    A = apexpy.Apex(2018.1,refh=300)
    babs = A.get_babs(89.9,100,100)
    print(babs)
    5.4328340291976928e-05

Then compare with: https://ngdc.noaa.gov/geomag-web/#igrfwmm. February 5th is closest to 0.1 of a year.

### apex_bvectors

    import apexpy
    A = apexpy.Apex(2018.1,refh=300)
    Be3, e3, Bd3, d3 = A.apex_bvectors(60,120,200)
    print(Be3,e3,Bd3,d3)
    (5.6937833948183995e-05, array([-0.04589213,  0.21240786, -0.93846172], dtype=float32), 5.2834532890467046e-05, array([-0.04945627,  0.22890414, -1.01134574], dtype=float32))

## Unit Testing
You can test everything by running pytest in the root directory of this repo.

## Misc
I branched off of master, which is why the change to the setup.py file is included. I should have branched off of develop.

### CODE REVIEW

**Comment by asreimer** [comment]
Hmm. My lack of experience with travisCI is showing. It looks like the `fortranapex.so` file isn't being installed into the right place? It's fine on my machine (Fedora 26, installed using `pip install .`)

**Comment by asreimer** [comment]
Oh I see. Python 2.7 builds are fine. Python 3 isn't.

Looking locally, for Python 3.6, the `fortranapex.so` file (Python 2.7) is named `fortranapex.cpython-36m-x86_64-linux-gnu.so` instead...

**Comment by asreimer** [comment]
Ok, remaining task is to fix the ctypes call in Windows. Looks like ctypes is used differently? Not sure, but appveyor tests are failing.

**Comment by asreimer** [comment]
@aburrell, no, none of the appveyor builds are succeeding.

I'm going to make a change the apex_bvectors method. To keep the naming in line with other methods, it should be called `bvectors_apex`. Then a `bvectors_qd` could also be made in the future. This mirrors the `basevectors_apex` naming scheme.

**Comment by ljlamarche** [comment]
Will this pull request be finished soon?  The feature it adds is exactly what I need to perform ExB velocity to electric field rotations.

**Comment by asreimer** [comment]
Done and working from my point of view. Just needs a merge.

**Comment by aburrell** [comment]
Windows is failing pretty much everywhere, so I'm ok with this.

**Pull request merged**
