### PR TITLE
adding support for numpy.ndarray and numpy.datetime64 to helpers.subsol

### PR DESCRIPTION
**Pull request by gregstarr**
This PR allows `helpers.subsol` to work with numpy arrays of `datetime64`.
```
import numpy as np
import apexpy

converter = apexpy.Apex()
mlon = np.arange(10)
times = np.datetime64("1966-03-10T10:00:00") + np.arange(10) * np.timedelta64(1, 'D')
mlt = converter.mlon2mlt(mlon[None, :], times[:, None])
print(mlt.shape)
```
`>>> (10, 10) `

I added a test to verify that getting the subsolar point of an array of times is the same as getting each time individually. Combined with the existing test, this verifies that the method is still correct.

Is this something you are interested in? If so, how would you want to handle this example?
```
import numpy as np
import apexpy

converter = apexpy.Apex()
lat = np.arange(10)
lon = np.arange(10)
times = np.datetime64("1966-03-10T10:00:00") + np.arange(10) * np.timedelta64(1, 'D')
mlat, mlt = converter.convert(lat[None, :, None], lon[None, None, :], 'geo', 'mlt', 100, times[:, None, None])
print(mlat.shape)
print(mlt.shape)
```
```
(1, 10, 10)
(10, 10, 10)
```

### CODE REVIEW

**Comment by gregstarr** [comment]
I made this PR off of master which obviously isn't ideal, but I couldn't get develop to work on my computer. I got the same errors as the CI on develop gets: ` AttributeError: function 'cofrm_' not found`

**Comment by aburrell** [comment]
Ok @gregstarr I will look into that error you mention on develop (useful feedback, and appreciated).  Also, looking over the code very briefly, it looks like it should merge into develop w/o issue.  I will also see if that can be done.

**Comment by gregstarr** [comment]
Hello, just checking in on this. Were you able to figure out the problems with develop?

**Comment by aburrell** [comment]
No, I've been taking leave since things have been so interesting in DC.  It's still on my list, thanks for the check-in.

**Comment by gregstarr** [comment]
Closing because this is a duplicate of #29

**Pull request closed without merging**
